const LIST_MENU = [
  {
    id: "m1",
    category: "PIZZA",
    name: "Cheese Lover Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 120000,
    url: "/images/menu/pizza/cheese-lover-pizza.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m2",
    category: "PIZZA",
    name: "Corn Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 110000,
    url: "/images/menu/pizza/corn-pizza.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m3",
    category: "PIZZA",
    name: "Funky Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 115000,
    url: "/images/menu/pizza/funky-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m4",
    category: "PIZZA",
    name: "Green Cream Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 120000,
    url: "/images/menu/pizza/green-cream-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m5",
    category: "PIZZA",
    name: "Greens Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 111000,
    url: "/images/menu/pizza/greens-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m6",
    category: "PIZZA",
    name: "Mashroom Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 150000,
    url: "/images/menu/pizza/mashroom-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m7",
    category: "PIZZA",
    name: "Meat Lover Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 180000,
    url: "/images/menu/pizza/meat-lover-pizza.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m8",
    category: "PIZZA",
    name: "Pepper Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 155000,
    url: "/images/menu/pizza/pepper-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m9",
    category: "PIZZA",
    name: "Pepperoni Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 159900,
    url: "/images/menu/pizza/pepperoni-pizza.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m10",
    category: "PIZZA",
    name: "Tomato Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 160000,
    url: "/images/menu/pizza/pizza-n-tomato.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m11",
    category: "PIZZA",
    name: "Veeg Cheese Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 160000,
    url: "/images/menu/pizza/veeg-cheese-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m12",
    category: "PIZZA",
    name: "Viggies Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 165000,
    url: "/images/menu/pizza/viggies-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m13",
    category: "DRINKS",
    name: "Blue Ocean",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 10000,
    url: "/images/menu/drinks/blue-ocean.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m14",
    category: "DRINKS",
    name: "Chocolate Milkshake",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 15000,
    url: "/images/menu/drinks/chocolate-milkshake.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m15",
    category: "DRINKS",
    name: "Cucumber Squash",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 18000,
    url: "/images/menu/drinks/cucumber-squash.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m16",
    category: "DRINKS",
    name: "Ice Choco",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 18000,
    url: "/images/menu/drinks/ice-choco.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m17",
    category: "DRINKS",
    name: "Ice Lemon Tea",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 11000,
    url: "/images/menu/drinks/ice-lemon-tea.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m18",
    category: "DRINKS",
    name: "Ice Tea",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 8000,
    url: "/images/menu/drinks/ice-tea.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m19",
    category: "RAMEN",
    name: "Classic Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 35000,
    url: "/images/menu/ramen/classic-ramen.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m20",
    category: "RAMEN",
    name: "Crab Stick Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 38000,
    url: "/images/menu/ramen/crab-stick-ramen.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m21",
    category: "RAMEN",
    name: "Curry Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 36500,
    url: "/images/menu/ramen/curry-ramen.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m22",
    category: "RAMEN",
    name: "Duck Meat Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 37000,
    url: "/images/menu/ramen/duck-meat-ramen.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m23",
    category: "RAMEN",
    name: "Ebi Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 40000,
    url: "/images/menu/ramen/ebi-ramen.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m24",
    category: "RAMEN",
    name: "Green Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 30000,
    url: "/images/menu/ramen/green-ramen.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m25",
    category: "RICE",
    name: "Chicken Katsu",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 35000,
    url: "/images/menu/rice/chicken-katsu.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m26",
    category: "RICE",
    name: "Greens Bowl",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 28000,
    url: "/images/menu/rice/greens-bowl.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m27",
    category: "RICE",
    name: "Healthy Rice Bowl",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 28000,
    url: "/images/menu/rice/healty-rice-bowl.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m28",
    category: "RICE",
    name: "Katsu Nasi Kuning",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 25000,
    url: "/images/menu/rice/katsu-nasi-kuning.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m29",
    category: "RICE",
    name: "Lemon Nasi Goreng",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 30000,
    url: "/images/menu/rice/lemon-nasi-goreng.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m30",
    category: "RICE",
    name: "Meat Potato Rice",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 33000,
    url: "/images/menu/rice/meat-potato-rice.jpg",
    bestSeller: false,
    recomended: false,
  },
];

export default LIST_MENU;
